var Arguments = require("./../arguments.js").Arguments,
  GenericResponse = require('./generic.js').GenericResponse
require('./../setimmediate.js')

/**
 * The request yielded by a single callback that is to be called by
 * the client.
 *
 * @param {Arguments} args The callback arguments or a serialized
 * object generated by a server side ArgsResponse. Since these are
 * callback arguments they should contain no callback
 * themselves.
 */
function ArgsResponse (args) {
  this.cbArgs = args
}

ArgsResponse.async = function (mr, hostApi) {
  var resp = new ArgsResponse()
  resp.mr = mr
  resp.hostApi = hostApi
  return resp
}

/**
 * Handle the response on the client side if it is of the correct
 * type.
 *
 * @param {Message} msg the raw message received by the server
 * @param {Request} request the request object that msg is a response
 * to.
 * @param {Function} doneCb Call this when you are done. It will be
 * called with no arguments on succes or an error object on error.
 * @return {Boolean} true if we handled it.
 */
ArgsResponse.maybeHandle = function (msg, request, doneCb) {
  if (msg.responseType != "ArgsResponse") return false
  if (!request.getCallback()) {
    doneCb(new Error("No real callback provided on the client."))
    return true
  }
  var cbArgs = new Arguments(msg.args),
    callArgs = cbArgs.forCalling(),
    callback = request.getCallback()

  // log.log("Received:", cbArgs.forSending(), "for", {fn: String(callback)})
  callback.apply(null, callArgs)
  setImmediate(doneCb)
  return true
}

ArgsResponse.prototype = Object.create(GenericResponse.prototype)

/**
 * The callback arguments serialized.
 *
 * @returns {Object} the object to be put through the API.
 */
ArgsResponse.prototype.forSending = function () {
  return {
    responseType: "ArgsResponse",
    args: this.cbArgs.forSending()
  }
}

ArgsResponse.prototype.send = function (sendCb) {
  if (this.mr) {
    // NOTE: ArgsRepsonse for connection cleanups are lazy. The
    // callback of the api call does the actual work of sending the
    // respinse.
    this.mr.call(sendCb, this.hostApi)
    return
  }

  sendCb(this.forSending())
}
module.exports = ArgsResponse
